language: node_js
node_js:
  - "7"

script:
  - ng build --env=dev

deploy:
  provider: cloudfoundry
  api: https://api.stage1.ng.bluemix.net
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASS
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  on:
    repo: GearBox/DDE-ang-node-test
    branch: travisci-test
