language: node_js
node_js:
  - "8"

branches:
only:
  - travisci-test

deploy:
  provider: cloudfoundry
  api: https://api.stage1.ng.bluemix.net
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASS
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  on:
    repo: GearBox/DDE-ang-node-test
