---
language: node_js
node_js:
  - "7"

before_install:
  - npm install -g @angular/cli
  - sudo pip install yamllint
  - npm install -g envsub

before_script:
  - "./tests/test-yamllint.sh"

script:
  - ng build --env=prod
  - envsub --env environment.prod.ts

deploy:
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: $BLUEMIX_USER_PROD
  password: $BLUEMIX_PASS_PROD
  organization: $BLUEMIX_ORGANIZATION_PROD
  space: $BLUEMIX_SPACE_PROD
  "on":
    repo: GearBox/DDE-ang-node-test
    branch: travisci-test
