---
language: node_js
node_js:
  - "7"

before_install:
  - npm install -g @angular/cli
  - sudo pip install yamllint

before_script:
  - "./tests/test-yamllint.sh"

script:
  - ng build --env=prod

deploy:
  provider: cloudfoundry
  api: https://api.stage1.ng.bluemix.net
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASS
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  "on":
    repo: GearBox/DDE-ang-node-test
    branch: master
