---
language: node_js
node_js:
  - "7"

before_install:
  - npm install @angular/cli
  - npm install csslint eslint html-lint tslint
  - sudo pip install yamllint
  - npm install -g envsub

before_script:
  - "./tests/test-yamllint.sh"
  - "./tests/test-csslint.sh"
  - "./tests/test-eslint.sh"
  - "./tests/test-html-lint.sh"
  - "./tests/test-shellcheck.sh"
  - "./tests/test-tslint.sh"

script:
  - envsub --env SEGMENT_KEY=$SEGMENT_KEY ./src/environments/environment.ts
  - ng build --env=dev

# deploy:
#   provider: cloudfoundry
#   api: https://api.stage1.ng.bluemix.net
#   username: $BLUEMIX_USER
#   password: $BLUEMIX_PASS
#   organization: $BLUEMIX_ORGANIZATION
#   space: $BLUEMIX_SPACE
#   "on":
#     repo: GearBox/Dynamic-dashboard-demo
#     branch: linting
